### ISSUE TITLE
OSC Trino deployments show warnings about OAuth2 

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/apps#2374]
After looking into the Trino coordinator logs, some rather nasty looking warnings continue to pop up about an `Oauth2 client not being initialized`. Here is a fragment of the error in the stacktrace: 
```
2022-09-03T14:37:56.260Z	WARN	http-worker-174	io.trino.server.ThrowableMapper	Request failed for /ui/api/query
java.lang.IllegalStateException: OAuth2 client not initialized
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	...
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` This warning also appears for for the routes `/ui/api/stats` and `/ui/api/cluster` in addition to `/ui/api/query`. It seems to occur 4 times per route in the logs before the server starts. In terms of configuring properties, the documentation was being followed for [setting up trino Oauth2](https://trino.io/docs/388/security/oauth2.html) as well as configuring the underlying TLS (see [here](https://trino.io/docs/388/security/internal-communication.html#configure-internal-tls) and [here](https://trino.io/docs/388/security/tls.html)). It also appears as if these warnings have been appearing for quite some time, as one of the steps I attempted in trying to fix this was reverting commit history, but it still seems to be appearing at least 5 commits back in history for `kfdefs/overlays/osc/osc-cl2`. Note we turned argocd sync off on that application (kfdefs-osc-cl2) to play with it, but this issue is also occuring in osc-cl1. Osc-cl2 is running trino version `388`.

/cc @erikerlandson 
/cc @HumairAK 
/cc @rimolive

**Comment by erikerlandson** [comment]
Link to beginning of slack channel thread
https://operatefirst.slack.com/archives/C03LCPTPZ6J/p1662161325454969

**Comment by erikerlandson** [comment]
A link to example coordinator log output:
[trino-coordinator-699d847b96-wcjkk-trino-coordinator.log](https://github.com/operate-first/apps/files/9482882/trino-coordinator-699d847b96-wcjkk-trino-coordinator.log)
